import './js/modal_window_close';
import './js/best_sellers_fetch';
import './js/best_sellers_render';
import './js/best_sellers_scroll_to_top';
import './js/category_chosen';
import './js/category_book_profile';
import './js/category';
import './js/change_theme';
import './js/modal_window_object';
// import './js/shopping_list';
import './js/athorization_modal_user';
import './js/authorization_modal_close';
import './js/support_Ukraine';
import './js/best_sellers_preload';